// src/components/Header.vue
<template>
  <header class="header">
    <nav :class="{ 'flex-container': true, loggedIn: userLoggedIn }">
      <router-link to="/"><img src="../assets/logo.svg" alt="Auth Vue"/></router-link>
      <a @click="logout" v-if="userLoggedIn">logout</a>
    </nav>
  </header>
</template>

<script>
import { mapState } from 'vuex';

export default {
  name: 'Header',
  computed: {
    ...mapState(['auth']),
    userLoggedIn() {
      return Object.keys(this.auth.userProfile).length > 0;
    }
  },
  methods: {
    logout() {
      this.$store.dispatch('logout');
    }
  }
};
</script>

<style lang="scss" scoped>
.header {
  padding: 2em 0;
}

.loggedIn {
  justify-content: space-between;
}
</style>

// firebase/auth-react-redux/src/components/Header.jsx
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { logout } from '../store/features/auth/authSlice';
import ReactIcon from './ReactIcon';

const Header = ({ className }) => {
  const { user } = useSelector((state) => state.auth);
  const isAuthenticated = Object.keys(user).length > 0;
  const dispatch = useDispatch();

  return (
    <header className={`${className} ${isAuthenticated ? 'flex justify-between' : ''}`}>
      <Link to="/" className="flex items-center justify-center">
        <ReactIcon className="mr-2" />
        <h1 className="font-asap text-2xl">Auth React-Redux</h1>
      </Link>
      {isAuthenticated && <button onClick={() => dispatch(logout())}>Logout</button>}
    </header>
  );
};

export default Header;
