// firebase/auth-react-redux/src/components/pages/Login.jsx
import { Link } from 'react-router-dom';
import PasswordField from '../PasswordField';
import { useApplyCSSClass } from '../../hooks';

const LogIn = () => {
  useApplyCSSClass('#root', ['h-full', 'md:bg-pale']);

  return (
    <>
      <div className="flex justify-center">
        <div className="bg-white pt-10 md:p-10 md:rounded md:shadow">
          <h1 className="text-center">Sign up for your account</h1>
          <form className="mt-12 space-y-5 pb-4 border-b border-dark mb-4 w-80">
            <input
              className="w-full border rounded-sm p-2 outline-none"
              type="email"
              placeholder="Enter email"
              autoComplete="off"
              required
            />
            <PasswordField className="w-full border rounded-sm p-2" />
            <button className="w-full border rounded-sm bg-react-blue p-2">Log In</button>
          </form>
          <div className="text-center text-sm">
            <div className="mb-2">Forgot your password?</div>
            <div>
              Don't have an account?{' '}
              <Link to="/register" className="underline">
                Register
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default LogIn;

// src/views/Login.vue
<template>
  <div id="login">
    <form class="form" @submit.prevent>
      <div class="form-control">
        <input
          id="email"
          type="email"
          placeholder="Enter email"
          autocomplete="off"
          required
          v-model="email"
        />
      </div>
      <div class="form-control">
        <input
          id="password"
          type="password"
          placeholder="Enter password"
          required
          v-model="password"
        />
      </div>
      <div class="form-control">
        <button class="btn" @click="login">Log in</button>
      </div>
    </form>
    <div>
      <span>Forgot your password?</span>
    </div>
    <div>
      <span>Don't have an account? <router-link to="/signup">Sign Up</router-link></span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Login',
  data() {
    return {
      email: '',
      password: ''
    };
  },
  methods: {
    login() {
      const { email, password } = this;
      this.$store.dispatch('login', { email, password });
    }
  }
};
</script>

<style lang="scss" scoped>
#login {
  margin: 0 auto;
  width: 50%;
}
</style>
